### ISSUE TITLE
Can't find the way to resize the output map

### ISSUE THREAD

**Issue by ohld** [swistakm/python-gmaps#10]
Hi everyone. You're package is brilliant! But there is no way to change the output map size. E.G. in Jupyter Notebook it is quite small. How can i do that?

**Comment by swistakm** [comment]
This lib does not output any maps. Are you sure that you use `python-gmaps` in your Jupyter Notebook? Can you share your code?

**Comment by swistakm** [comment]
I close this issue. Feel free to reopen when you will be able to provide more feedback.
