### ISSUE TITLE
Can't save the output map.

### ISSUE THREAD

**Issue by ohld** [swistakm/python-gmaps#11]
Hi everyone. You're package is brilliant! But there is no way to save the output map. It will be quite useful if you need to make lots of maps with a script. How can I do that? Can you add this to your library?

**Comment by swistakm** [comment]
This lib does not output any maps. Are you sure that you use `python-gmaps` in your Jupyter Notebook? Can you share your code?

**Comment by swistakm** [comment]
I close this issue. Feel free to reopen when you will be able to provide more feedback.
