### ISSUE TITLE
Adding "reverse geocoding restricted by type" feature

### ISSUE THREAD

**Issue by gabbork** [swistakm/python-gmaps#7]
As explained in the gmaps api doc https://developers.google.com/maps/documentation/geocoding/intro#reverse-restricted
reverse method need 2 extra parameters, **result_type** dictionary and **location_type** dictionary.

Should be a very quick fix
https://github.com/swistakm/python-gmaps/blob/master/src/gmaps/geocoding.py#L39

**Comment by swistakm** [comment]
fixed by #8
